"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { useParams } from "next/navigation";
import { apiGet, type FieldAnalytics, type IrrigationRecord, type SensorReading } from "@/lib/api";
import styles from "../../data-page.module.css";
type Field = { field_id:number; farmer_id:number; name:string; area:string|number; latitude:number|string|null; longitude:number|string|null; soil_type:string|null; soil_ph:string|number|null; organic_carbon:string|number|null; electrical_conductivity:string|number|null; sunlight_hours:string|number|null; region:string|null; irrigation_type:string|null; water_source:string|null; mulching_used:string|null; crop_name:string|null; growth_stage:string|null; planting_date:string|null };
export default function FieldDetailsPage(){
 const params=useParams<{id:string}>();const fieldId=params.id;const [field,setField]=useState<Field|null>(null);const [reading,setReading]=useState<SensorReading|null>(null);const [analytics,setAnalytics]=useState<FieldAnalytics|null>(null);const [history,setHistory]=useState<IrrigationRecord[]>([]);const [error,setError]=useState("");const [loading,setLoading]=useState(true);
 useEffect(()=>{let live=true;Promise.all([apiGet<Field[]>("/api/fields"),apiGet<SensorReading>(`/api/sensor/latest/${fieldId}`).catch(()=>null),apiGet<FieldAnalytics>(`/api/analytics/${fieldId}`).catch(()=>null),apiGet<IrrigationRecord[]>(`/api/irrigation/history/${fieldId}`).catch(()=>[])]).then(([fields,r,a,h])=>{if(!live)return;const match=fields.find((item)=>item.field_id===Number(fieldId));if(!match)throw new Error("Field not found or you do not have access.");setField(match);setReading(r);setAnalytics(a);setHistory(h);}).catch((e:unknown)=>{if(live)setError(e instanceof Error?e.message:"Could not load field details.");}).finally(()=>{if(live)setLoading(false);});return()=>{live=false;};},[fieldId]);
 return <main className={styles.page}><header className={styles.header}><Link href="/">← Dashboard</Link><h1>Field details</h1></header>{loading&&<p className={styles.notice}>Loading field details…</p>}{error&&<p className={styles.error} role="alert">{error}</p>}{field&&<><section className={styles.card}><p>Field #{field.field_id} · {field.region||"Region not set"}</p><h2>{field.name}</h2><p>{field.crop_name||"No crop registered"} · {field.growth_stage||"Growth stage not set"}</p><div className={styles.metrics}>{[["Area",`${field.area} ha`],["Soil",field.soil_type||"—"],["pH",field.soil_ph??"—"],["Organic carbon",field.organic_carbon??"—"],["Electrical conductivity",field.electrical_conductivity??"—"],["Irrigation",field.irrigation_type||"—"],["Water source",field.water_source||"—"],["Mulching",field.mulching_used||"—"]].map(([key,value])=><article className={styles.metric} key={key}><span>{key}</span><strong>{value}</strong></article>)}</div></section><section className={styles.metrics}><article className={styles.metric}><span>Current soil moisture</span><strong>{reading?`${Number(reading.soil_moisture).toFixed(1)}%`:"No sensor reading"}</strong></article><article className={styles.metric}><span>Average moisture</span><strong>{analytics?.sensor.average_soil_moisture==null?"—":`${Number(analytics.sensor.average_soil_moisture).toFixed(1)}%`}</strong></article><article className={styles.metric}><span>Schedules</span><strong>{analytics?.irrigation.irrigation_count??0}</strong></article></section><section className={styles.card}><h2>Recent recommendations</h2>{history.length?history.slice(0,5).map((item)=><article className={styles.row} key={item.schedule_id}><div><strong>{item.irrigation_need} · {item.irrigation_required?"Irrigation required":"No irrigation required"}</strong><small>{item.reason||""}</small></div><time>{new Date(item.created_at).toLocaleString()}</time></article>):<p>No irrigation history recorded.</p>}</section><div className={styles.actions}><Link href={`/history?field=${field.field_id}`}>View history</Link><Link href={`/analytics?field=${field.field_id}`}>View analytics</Link><Link href="/reports">Open reports</Link></div></>}</main>;
}
